baseURL = "/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "TECINPACT Techno Guide"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
disqusShortname = "tecinpact"

# Google Analytics
googleAnalytics = "UA-172360495-1"

[params]
title = "I'm Nushan Kodikara"
author = "Tecinpact"
description = "Welcome Visitor! here you can find out new technologies, Reviews, suggestions about technologies and step-by-step guides to the EASY World. If you need any help, Just contact Me."
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-facebook"
title = "Facebook"
url = "https://facebook.com/nushan.kodikara.7"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/nushankodikara/"

[[params.socialIcons]]
icon = "fa-whatsapp"
title = "Whatsapp"
url = "https://wa.me/94719988189"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/____nushan_"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:nushankodi@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 1
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 3
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Search"
  weight = 100
  identifier = "search"
  url = "/search/"

  [[menu.main]]
  name = "Portfolio"
  weight = 4
  identifier = "portfolio"
  url = "/portfolio/"

[outputs]
  home = ["HTML", "JSON"]
