DefaultContentLanguage = "en"
baseURL = "https://tecinpact.tk/"
enableEmoji = true
languageCode = "en"
summarylength = 10
theme = "anatole"
title = "TECINPACT Technology Guide"

# Enable Disqus
disqusShortname = "tecinpact"

# Google Analytics
googleAnalytics = "UA-172360495-1"

[params]
adsenseID = "ca-pub-2375766996268537"
author = "Tecinpact"
customCss = []
description = "Welcome Visitor! Here you can find out new technologies, Reviews, suggestions about technologies and step-by-step guides to the EASY World."
favicon = "favicons/"
images = ["images/site-feature-image.png"]
keywords = ""
mainSections = ["post"]
profilePicture = "images/profile.jpg"
title = "I'm Nushan Kodikara"

## Math settings
[params.math]
enable = false # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex" # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-facebook"
title = "Facebook"
url = "https://www.facebook.com/Tecinpact"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/Tecinpact"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/nushankodikara"

[[params.socialIcons]]
icon = "fa-telegram"
title = "Telegram"
url = "https://t.me/tecinpact"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/Tecinpact"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:tecinpactagencies@gmail.com"

## Menu items

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/post/"
weight = 2

[[menu.main]]
identifier = "cookies"
name = "Cookies"
url = "/cookies/"
weight = 3

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 4

[[menu.main]]
identifier = "portfolio"
name = "Portfolio"
url = "/portfolio/"
weight = 5

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 100

[outputs]
home = ["HTML", "RSS", "JSON"]
