baseURL = "https://www.tecinpact.tk/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "TECINPACT Techno Guide"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
disqusShortname = "tecinpact"

# Google Analytics
googleAnalytics = "UA-172360495-1"

[params]
title = "I'm Nushan Kodikara"
author = "Tecinpact"
description = "Welcome Visitor! Here you can find out new technologies, Reviews, suggestions about technologies and step-by-step guides to the EASY World."
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
adsenseID = "ca-pub-2375766996268537"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-facebook"
title = "Facebook"
url = "https://www.facebook.com/Tecinpact"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/Tecinpact"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/nushankodikara"

[[params.socialIcons]]
icon = "fa-telegram"
title = "Telegram"
url = "https://t.me/tecinpact"

[[params.socialIcons]]
icon = "fa-whatsapp"
title = "Whatsapp"
url = "https://chat.whatsapp.com/K4aWxjBIfw38GNuupCNmTO"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/Tecinpact"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:tecinpactagencies@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 1
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 3
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Portfolio"
  weight = 4
  identifier = "portfolio"
  url = "/portfolio/"

  [[menu.main]]
  name = "Search"
  weight = 100
  identifier = "search"
  url = "/search/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
